from pydantic import BaseModel, EmailStr, field_validator
from datetime import datetime
from typing import Optional


class UserCreate(BaseModel):
    email: EmailStr
    password: str
    role: str  # New field

    # Optional: Logic to force only "buyer" or "seller"
    @field_validator('role')
    def role_must_be_valid(cls, v):
        if v.lower() not in ['buyer', 'seller']:
            raise ValueError('Role must be either "buyer" or "seller"')
        return v.lower()
# WHAT YOU SEND BACK (Hide the password!)
class UserResponse(BaseModel):
    id: int
    email: str
    role: str
    created_at: datetime

    class Config:
        # This tells Pydantic to read data from the SQL model
        from_attributes = True

class UserLogin(BaseModel):
    email: EmailStr
    password: str

class JobResponse(BaseModel):
    id: int
    title: str
    status: str       # PROCESSING, RUNNING, COMPLETED
    created_at: datetime
    
    # Optional: Include these if you want to show download links in the list
    original_code_url: str
    original_data_url: str

    class Config:
        from_attributes = True

# In app/schemas.py

class AgentList(BaseModel):
    id: str           # e.g. "agent_550e..."
    status: str       # IDLE, BUSY, OFFLINE
    gpu_model: Optional[str] = "Unknown"
    ram_total: Optional[str] = "Unknown"
    last_heartbeat: datetime

    class Config:
        from_attributes = True

class AgentHeartbeat(BaseModel):
    id: str           # The Agent's ID (e.g., "agent_550e...")
    status: str       # Current state: "IDLE" or "BUSY" (or "WORKING")

class AgentRegister(BaseModel):
    id: str             # The UUID generated by the script (e.g. "agent_550e...")
    email: str          # The Owner's Email (to link Machine -> Human)
    gpu_model: Optional[str] = "Unknown"
    ram_total: Optional[str] = "Unknown"

# In app/schemas.py

class TaskRequest(BaseModel):
    agent_id: str

class TaskResponse(BaseModel):
    task_id: int | None = None  # If None, no work is available
    job_id: int | None = None
    
    # The 3 Ingredients needed to cook
    code_url: str | None = None
    requirements_url: str | None = None
    chunk_data_url: str | None = None

class TaskComplete(BaseModel):
    agent_id: str
    task_id: int
    result_url: str  # The Supabase URL where the agent uploaded the result