#!/bin/bash
set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 Setting up Grid-X Worker Environment...${NC}"

# 1. System Check
echo -e "\n${BLUE}[1/5] Checking Prerequisites...${NC}"

if ! command -v python3 &> /dev/null; then
    echo -e "${RED}❌ Python 3 is not installed.${NC}"
    echo "Please install Python 3.10 or higher."
    exit 1
fi

if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker is not installed.${NC}"
    echo "Please install Docker Desktop or Docker Engine."
    exit 1
fi
echo -e "${GREEN}✅ System checks passed.${NC}"

# 2. Virtual Environment
echo -e "\n${BLUE}[2/5] Setting up Python Environment...${NC}"
if [ ! -d "venv" ]; then
    python3 -m venv venv
    echo -e "${GREEN}✅ Created virtual environment in ./venv${NC}"
else
    echo -e "${GREEN}✅ Virtual environment already exists.${NC}"
fi

source venv/bin/activate
pip install --upgrade pip
if [ -f "worker/requirements.txt" ]; then
    pip install -r worker/requirements.txt
else
    echo -e "${YELLOW}⚠️  worker/requirements.txt not found. Installing base dependencies...${NC}"
    pip install requests python-dotenv docker
fi

# 3. Configuration
echo -e "\n${BLUE}[3/5] Configuring Worker...${NC}"

# Prompt for Backend URL
read -p "Enter Backend URL [http://localhost:8000]: " USER_BACKEND
USER_BACKEND=${USER_BACKEND:-http://localhost:8000}

# Prompt for Worker Email (CRITICAL FOR REGISTRATION)
read -p "Enter Worker Email (must match a registered user) [agent@gridx.com]: " USER_EMAIL
USER_EMAIL=${USER_EMAIL:-agent@gridx.com}

# Write a robust worker_config.env
cat > worker_config.env <<EOF
# Grid-X Worker Configuration
# Generated by setup_worker.sh on $(date)

# Backend Connection
BACKEND_URL=${USER_BACKEND}

# Worker Identity
# Email MUST match a registered user on the platform
WORKER_EMAIL=${USER_EMAIL}

# Resource Limits (Optional overrides)
# WORKER_CPU_LIMIT=2.0
# WORKER_MEMORY_LIMIT=4g
EOF

echo -e "${GREEN}✅ Configuration saved to worker_config.env${NC}"
grep "WORKER_EMAIL" worker_config.env

# 4. Docker Image
echo -e "\n${BLUE}[4/5] Building Secure Executor Image...${NC}"
docker build -t secure-executor-base -f Dockerfile.base .
echo -e "${GREEN}✅ Docker image 'secure-executor-base' built.${NC}"

# 5. Start Script
echo -e "\n${BLUE}[5/5] Generating Start Script...${NC}"
cat > start_worker.sh <<'EOF'
#!/bin/bash
# Start script for Grid-X Worker

# Load configuration safely
if [ -f "worker_config.env" ]; then
    # Load variables from file, ignoring comments
    export $(grep -v '^#' worker_config.env | xargs)
fi

# Validate critical variables
if [ -z "$WORKER_EMAIL" ]; then
    echo "❌ ERROR: WORKER_EMAIL is not set in worker_config.env"
    exit 1
fi

echo "🚀 Starting Grid-X Worker"
echo "========================"
echo "Backend: ${BACKEND_URL}"
echo "Email:   ${WORKER_EMAIL}"

# Activate venv
source venv/bin/activate

# Run Worker
# 2>&1 | tee worker.log captures both stdout and stderr
python worker/main.py 2>&1 | tee worker.log
EOF

chmod +x start_worker.sh
echo -e "${GREEN}✅ Created ./start_worker.sh${NC}"

echo -e "\n${GREEN}🎉 Setup Complete!${NC}"
echo -e "To start the worker, run:\n"
echo -e "    ${YELLOW}./start_worker.sh${NC}\n"
